---
# tasks file for toshakins.docker-compose
- name: collect some facts
  setup:
    gather_subset:
      - min

- name: add Docker repository
  block:
    - name: docker | add apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: docker | add apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: update package manager
  apt:
    name: '*'
    state: latest

- name: install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes

- name: add current user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: "docker"

- name: set passwords
  set_fact:
    drive_db_password: "{{ lookup('password', '/tmp/drive_db_password length=24') }}"
    drive_admin_password: "{{ lookup('password', '/tmp/drive_admin_password length=24') }}"

- name: write docker compose template
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    backup: yes

- name: start docker
  service:
    name: docker
    state: started

- name: start seafile
  become: yes
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}"

## to do: do not install gcc if pip deps installed. Check if possible to avoid 80 port open. Resize ebs?
