---
# tasks file for toshakins.docker-compose
- name: collect some facts
  setup:
    gather_subset:
      - min

- name: update package manager
  yum:
    name: '*'
    state: latest

- name: install pip
  yum:
    name: python-pip
    state: latest

- name: install gcc
  yum:
    name: gcc
    state: latest
  become: yes

- name: install docker deps
  pip:
    name:
      - docker==4.2.2
      - docker-compose==1.26.2
      - PyYAML==5.3.1
  become: yes

- name: remove gcc
  yum:
    name: gcc
    state: absent

- name: create directory for local executables
  file:
    path: "/home/{{ ansible_user }}/bin"
    state: directory
    mode: u=rwx

- name: get docker compose file
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: "/home/{{ ansible_user }}/bin/docker-compose"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rx,g=rx,o=rx
  become: yes

- name: set passwords
  set_fact:
    drive_db_password: "{{ lookup('password', '/tmp/drive_db_password length=24') }}"
    drive_admin_password: "{{ lookup('password', '/tmp/drive_admin_password length=24') }}"

- name: write docker compose template
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    backup: yes

- name: start docker
  service:
    name: docker
    state: started

- name: start seafile
  become: yes
  docker_compose:
    project_src: "/home/{{ ansible_user }}"

## to do: do not install gcc if pip deps installed. Check if possible to avoid 80 port open. Resize ebs?
